Add tools and Debian packaging for parsing dlopen ELF notes
systemd/package-notes pull request #33
Opened 2024-05-05 16:15 UTC by bluca

Spec and implementation at https://github.com/systemd/systemd/pull/32234

2024-05-07 20:12 UTC, keszybz commented on dlopen-notes.py
> +        sys.exit(1)
`%` should not be used in new code. Really.

```python
sys.exit(f'Usage: {sys.argv[0]} …')
```

2024-05-07 20:54 UTC, keszybz commented on dlopen-notes.py
> +        sonames.update(dlopen_notes_parse(sys.argv[i]))
```
for filename in sys.argv[1:]:
    sonames.update(dlopen_notes_parse(filename))
```

2024-05-07 20:54 UTC, keszybz commented on dlopen-notes.py
> +    with open(elf, 'rb') as f:
`with` is actually not useful here, since (read-only) open files are just another resource managed automatically by python and the system.

2024-05-07 20:54 UTC, keszybz commented on dlopen-notes.py
> +                            priority = 'recommended'
`priority = e.get('priority', 'recommended')` ?

2024-05-08 21:17 UTC, bluca commented
> I pushed another commit to rework the output to have more postprocessing.

Merged into the first commit with Co-authored-by - also added CI, and added back a way to print a "soname priority" list, that I need for the Debian tool, behind a new option

2024-05-08 21:46 UTC, bluca commented
I have no idea why it errors out in the CI, the string seems fine... also works locally, any idea?

2024-05-08 22:46 UTC, behrmann commented
The bit
```
[{"feature":"fido2","description":"Support fido2 for encryption and authentication.","priority":"required","soname":["libfido2.so.1"]}]
```
in the output makes me think that the else path here
```python
            try:
                if not isinstance(note_desc, str):
                    text = note_desc.decode('utf-8').rstrip('\0')
                else:
                    text = note_desc
                    print(text)
            except UnicodeDecodeError as e:
                raise ValueError(f'{filename}: Invalid UTF-8 in .note.dlopen n_desc') from e
```
is taken, but when I copy the above JSON into Emacs, it has a trailing null byte, which gives me the same error
> json.decoder.JSONDecodeError: Extra data: line 1 column 136 (char 135)

Yes, unfortunately strings in Python can have null bytes, so stripping that might be what's needed.

2024-05-08 22:54 UTC, bluca commented
Indeed stripping that side of the if fixes the issue, thanks

2024-05-09 08:33 UTC, keszybz requested changes

2024-05-09 08:33 UTC, keszybz commented on dlopen-notes.py
> +    return sonames
```python
def dictify(f):
    def wrap(*args, **kwargs):
        return dict(f(*args, **kwargs))
    return functools.update_wrapper(wrap, f)

@dictify
def group_by_soname(notes):
    for note in notes:
        for element in note:
            priority = element.get('priority', 'recommended')
            for soname in element['soname']:
                yield soname, priority
```
?

2024-05-09 08:33 UTC, keszybz commented on test/test.py
> +import unittest
Let's not use unittest, it's an unproductive java-inspired monstrosity.

Just drop the `class` boilerplate and pytest will pick up the test with any issue.

2024-05-09 09:16 UTC, merged